#!/bin/bash

export DIRECTORIO_SHIELD=/etc/SHIELD
export DIRECTORIO_DEL_NUCLEO=${DIRECTORIO_SHIELD}/core

mkdir usr_$USER


# Crear archivos de configuración de modulos habilitados
echo ${DIRECTORIO_SHIELD}/modulos/deComando/mockModulo/mockModulo : on > ${DIRECTORIO_SHIELD}/usr_${USER}/ConfigModDeComando_${USER}
echo ${DIRECTORIO_SHIELD}/modulos/deComando/Seguridad/Seguridad : off >> ${DIRECTORIO_SHIELD}/usr_${USER}/ConfigModDeComando_${USER}
echo ${DIRECTORIO_SHIELD}/modulos/deComando/auditoria/auditoria : off >> ${DIRECTORIO_SHIELD}/usr_${USER}/ConfigModDeComando_${USER}
echo ${DIRECTORIO_SHIELD}/modulos/deComando/controlDeCesiones/controlDeCesiones : off >> ${DIRECTORIO_SHIELD}/usr_${USER}/ConfigModDeComando_${USER}

echo ${DIRECTORIO_SHIELD}/modulos/periodicos/mockPeriodicos/mockPeriodicos : on > ${DIRECTORIO_SHIELD}/usr_${USER}/ConfigModPeriodicos_${USER}   
echo ${DIRECTORIO_SHIELD}/modulos/periodicos/controlDeCarga/controlDeCarga : off >> ${DIRECTORIO_SHIELD}/usr_${USER}/ConfigModPeriodicos_${USER}
echo ${DIRECTORIO_SHIELD}/modulos/periodicos/limitaciones/limitaciones : off >> ${DIRECTORIO_SHIELD}/usr_${USER}/ConfigModPeriodicos_${USER}   
echo ${DIRECTORIO_SHIELD}/modulos/periodicos/limitacionDeTraficoDeRed/limitacionDeTraficoDeRed : off >> ${DIRECTORIO_SHIELD}/usr_${USER}/ConfigModPeriodicos_${USER}   

# Crear archivo de inicialización
echo '#!/bin/bash' > ${DIRECTORIO_SHIELD}/usr_${USER}/inicializar
echo export CONFIG_PERIODICOS=${DIRECTORIO_SHIELD}/usr_${USER}/ConfigModPeriodicos_${USER} >> ${DIRECTORIO_SHIELD}/usr_${USER}/inicializar
echo export CONFIG_DE_COMANDO=${DIRECTORIO_SHIELD}/usr_${USER}/ConfigModDeComando_${USER} >> ${DIRECTORIO_SHIELD}/usr_${USER}/inicializar
echo export MODULOS_DE_COMANDO_ACTIVOS=${DIRECTORIO_SHIELD}/usr_${USER}/nombresDeModulosDeComando_${USER} >> ${DIRECTORIO_SHIELD}/usr_${USER}/inicializar
echo export MODULOS_PERIODICOS_ACTIVOS=${DIRECTORIO_SHIELD}/usr_${USER}/nombresDeModulosPeriodicos_${USER} >> ${DIRECTORIO_SHIELD}/usr_${USER}/inicializar
echo export INTERVALO_PERIODICOS=20s >> ${DIRECTORIO_SHIELD}/usr_${USER}/inicializar
echo export INTERVALO_VERIFICAR_CAMBIOS=30s >> ${DIRECTORIO_SHIELD}/usr_${USER}/inicializar
echo export PROMPT_PRINCIPAL=\'Ingrese un comando,o teclee salir para terminar: \' >> ${DIRECTORIO_SHIELD}/usr_${USER}/inicializar
echo export PATH_ANTIGUA=$PATH >> ${DIRECTORIO_SHIELD}/usr_${USER}/inicializar
echo export PATH=${PATH}:${DIRECTORIO_DEL_NUCLEO} >> ${DIRECTORIO_SHIELD}/usr_${USER}/inicializar
echo cd $HOME >> ${DIRECTORIO_SHIELD}/usr_${USER}/inicializar
echo core >> ${DIRECTORIO_SHIELD}/usr_${USER}/inicializar


# Crear archivo de desinicializacion
echo '#!/bin/bash' > ${DIRECTORIO_SHIELD}/usr_${USER}/desinicializar
echo unset CONFIG_PERIODICOS >> ${DIRECTORIO_SHIELD}/usr_${USER}/desinicializar
echo unset CONFIG_DE_COMANDO >> ${DIRECTORIO_SHIELD}/usr_${USER}/desinicializar
echo unset MODULOS_DE_COMANDO_ACTIVOS >> ${DIRECTORIO_SHIELD}/usr_${USER}/desinicializar
echo unset MODULOS_PERIODICOS_ACTIVOS >> ${DIRECTORIO_SHIELD}/usr_${USER}/desinicializar
echo unset INTERVALO_PERIODICOS >> ${DIRECTORIO_SHIELD}/usr_${USER}/desinicializar
echo unset INTERVALO_VERIFICAR_CAMBIOS >> ${DIRECTORIO_SHIELD}/usr_${USER}/desinicializar
echo unset PROMPT_PRINCIPAL >> ${DIRECTORIO_SHIELD}/usr_${USER}/desinicializar
echo export PATH=PATH_ANTIGUA > ${DIRECTORIO_SHIELD}/usr_${USER}/desinicializar

# Agregar archivos de inicio y salida a basrc y bash_logout
echo source ${DIRECTORIO_SHIELD}/usr_${USER}/inicializar >> ${HOME}/.bashrc

echo source ${DIRECTORIO_SHIELD}/usr_${USER}/desinicializar >> ${HOME}/.bash_logout
